### PR TITLE
feat: Added an explanation for The Logo Game (solves #84)

### PR DESCRIPTION
**Pull request by YashasviChaurasia**
Added Explanation on how to play the logo game in Step by Step Manner

Screenshot 2022-08-04 at 5 08 33 PM

Open Issue#84

### CODE REVIEW

**Comment by nobeeakon** [comment]
Code looks ok, but I wonder if we could make the text smaller ,  this way it is using a lot of vertical space. Mmm what about using the original proposal in #84 ? :  "_Select all logos that are exactly the same, and give them a name like "en:EU Organic" and a type like "label_"."

**Comment by YashasviChaurasia** [comment]
Ok, so should I just change the text according to proposal #84 and modify the file accordingly?
Or I should simply reduce the text of the current text?

Kindly help me with how to proceed.

**Comment by nobeeakon** [comment]
@YashasviChaurasia  you can make your own proposal if you are not fully convinced by  the text in #84 , yet I think it should be a 1 line explanation

**Comment by YashasviChaurasia** [comment]
OK, No issues I will quickly change the code.
Thank you

**Comment by YashasviChaurasia** [comment]
@nobeeakon I have modified the text.
Thank you

**Review by nobeeakon — APPROVED** [review]

**Comment by alexfauquette** [comment]
Congrats for your first contirbution 🎉

If you think an additional explanation should be added. It might be possible to use [`Accordion`](https://mui.com/material-ui/react-accordion/) to allow expending a more detailed explainations

**Comment by YashasviChaurasia** [comment]
Thank You for your guidance @nobeeakon @alexfauquette .
Really grateful for your help and assistance.

**Pull request merged**
