### PR TITLE
UX iteration on question game

### LINKED ISSUE #243: Enlarge the insight image when clicked
Often we need to look at the image linked to the insight to see if the prediction is correct. However, the text is sometimes small (see screenshot for example), and we need to enlarge the image to perform the check.
It would be convenient to be able to enlarge the image (all images actually) with a click. 

Capture d’écran du 2022-10-03 10-58-01

### LINKED ISSUE #261: Make more visible detected logo in question games
We currently display the detected logo from `universal-logo-detector` model in the "resume" panel (see screenshot).
This information is really useful for annotation, as it allows us to go much faster: we only have to focus on the cropped logo, we don't have to look for it on the full image.

Proposal: move the logo next to the main image. I'm opened to proposal for ideas of the best way to display this crop (and to explain to the users that it was the part of the image that triggered the prediction).

On a related note, I plan to add a new `data->bounding_box` field in insight table that will provide a unified way of knowing the area of interest, for regex, object detection models and universal-logo detector alike.
Capture d’écran du 2022-10-10 14-03-04

### LINKED ISSUE #278: feat: allowing users to rotate images
### Problem
In the [HungerGames questions game](https://hunger.openfoodfacts.org/questions), the displayed images of the product are often badly rotated.

### Proposed solutions
Allowing users to rotate the images. 
* It might even be saved in the database to better the quality of the rotation of images.

### Additional context
image

### LINKED ISSUE #346: Reintroduce zoom in a way that works for everyone
### What
- Zoom was removed: https://github.com/openfoodfacts/hunger-games/issues/81
- The images are not loaded on the right
- as a result, there's no way to zoom
- Even zooming that loads the image after clicking is ok, no need to preload the full resolution image

image

### PR DESCRIPTION
**Pull request by alexfauquette**
[netlify preview](https://deploy-preview-358--warm-cannoli-79bbb2.netlify.app/)
image

----

Fix #346
Part of #302
Fix #261
Fix #278
Fix #243

---

## Saving space on mobile

<table>
<tr>
	<td> Before
	<td> After

<tr>
	<td>
	<td>
</table>

### CODE REVIEW

**Comment by alexfauquette** [comment]
With the logo example

image

**Comment by alexfauquette** [comment]
Show logo extracted when available (in bottom right only on desktop)
image

**Comment by alexfauquette** [comment]
Add a button to open the image on full-screen

image

The main image is full-size, the other are still 400px ones

**Comment by teolemon** [comment]
For the category game, in responsive, I would really put the product name above the fold, somehow

**Review by teolemon — APPROVED** [review]
Great batch of usability improvements

**Pull request merged**
