### PR TITLE
fix: capitalize country names.

### PR DESCRIPTION
**Pull request by Sudhanva-Nadiger**
### What
- Country names were in small letters
- Now the first letter has been capitalized 

### Fixes bug(s)
- #386 

### Part of 
- #37

### CODE REVIEW

**Comment by alexfauquette** [comment]
`id`s can not be overridden. It's the key used to communicate with servers. Same for `countryNames`. We need the `'en:....'` to know what is the standard name of the country

The trick is to distinguish e value and the displayed text: https://github.com/openfoodfacts/hunger-games/issues/386#issuecomment-1335476404

**Comment by Sudhanva-Nadiger** [comment]
ohh yeah yeah got it!!! Like this ?
image
but if we type anything not in the list it shows no options noe

**Comment by alexfauquette** [comment]
> but if we type anything not in the list it shows no options noe

I don't get your point. If you update the PR, I could have a look to the behavior

**Comment by Sudhanva-Nadiger** [comment]
image

#
This is what i was asking ! in the previous comment. If we type anything which is not in country names it shows no options !

**Comment by alexfauquette** [comment]
Make sense that it does not show options if it's not part of the options. We put countries of the first countries concerned by eco-score. But you can use [`countries.json`](https://github.com/openfoodfacts/hunger-games/blob/c530360ad0b0e9475b49fcbfa30bec1b85ad39cb/src/assets/countries.json?rgh-link-date=2022-12-02T16%3A07%3A03Z#L643-L648) to get all the countries with product in OFF

**Comment by Sudhanva-Nadiger** [comment]
> Make sense that it does not show options if it's not part of the options. We put countries of the first countries concerned by eco-score. But you can use [`countries.json`](https://github.com/openfoodfacts/hunger-games/blob/c530360ad0b0e9475b49fcbfa30bec1b85ad39cb/src/assets/countries.json?rgh-link-date=2022-12-02T16%3A07%3A03Z#L643-L648) to get all the countries with product in OFF

Yeah, but we are currently using some of the country names, should we provide all countries as options in the card?

**Comment by Sudhanva-Nadiger** [comment]
Hey I have opened a new [pr](https://github.com/openfoodfacts/hunger-games/pull/522), this window whitelisted file names giving me lots of trouble, so had to do lots of branch lol and send pr.

**Pull request closed without merging**
