### PR TITLE
feat: Allow to remove some logos from deep search

### PR DESCRIPTION
**Pull request by alexfauquette**
Pressing remove will remove selected logos from the list. No request is sent to the server

image

### CODE REVIEW

**Comment by VaiTon** [comment]
Since they are not really removed could we rename the button to "Hide"?

**Review by VaiTon — APPROVED** [review]
LGTM apart from the comment above!

**Comment by alexfauquette** [comment]
> Since they are not really removed could we rename the button to "Hide"?

From the point of view of the web page, they are removed.

The app has two arrays:
- `annotatedLogos`: The logos that are annotated and that we can use to fetch more logos
- `logosToAnnotate`: The logo fetched by the API that needs to be annotated

So this function removes those logos from the app memory
```jsx
const removeSelectedLogos = () => {
    setLogosToAnnotate((prev) => prev.filter((logo, index) => !logo.selected));
  };
```

Is their something in particular that let you say they are just hidden?

**Comment by VaiTon** [comment]
"Remove" made me think about "remove logo from the server", but I'm ok with either

**Pull request merged**
