### PR TITLE
fix: show existing categories in categories questions

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
### Change log

- Shows existing categories in the category questions

### Screenshot

Screenshot (347)
Screenshot (346)

### Part of 

- Closes issue #220

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@teolemon @alexfauquette kindly review

**Review by alexfauquette — APPROVED** [review]
I've been scared by the number of files but sounds good :)

Thanks for your contribution

**Comment by abhilipsasahoo03** [comment]
> I've been scared by the number of files but sounds good :)
> 
> Thanks for your contribution

Hi, just a trivial question. Is there any chance this can be counted under Hacktoberfest?

**Comment by alexfauquette** [comment]
Maybe, I've no idea about how hacktoberfest is working

**Comment by abhilipsasahoo03** [comment]
> Maybe, I've no idea about how hacktoberfest is working

Oh ok. No issues. Thanks for merging!

**Comment by teolemon** [comment]
Note: Crowdin does replicate change automatically from the source file

**Comment by abhilipsasahoo03** [comment]
> Note: Crowdin does replicate change automatically from the source file
I was unaware of that. Thank you for letting me know.

**Pull request merged**
