### PR TITLE
feat: turn product details into a more legible table (solves #123)

### PR DESCRIPTION
**Pull request by nobeeakon**
### What
- table in product information, makes it more readable, as suggested in #123

### Screenshot
imagen

### Fixes bug(s)
- #123

### CODE REVIEW

**Comment by VaiTon** [comment]
@nobeeakon also here, there are workflow related changes. Should we include them in this PR?

**Comment by nobeeakon** [comment]
hey @VaiTon , yeah, thanks for the comment, no, those shouldn't be there, please let me check ...

**Comment by teolemon** [comment]
@nobeeakon unrelated but try to give explicit names to the PRs, with semantic prefixes, eg: 
"feat: turn product details into a more legible table"

**Comment by nobeeakon** [comment]
mmmm, well, some PRs are missing in the `master` of the repo. Those other PRs are not mine (2 from @alexfauquette , 2 CI changes from @teolemon ), but  existed in the `master`  (and at some point were reverted?).  @teolemon do you know why those are missing?

**Comment by VaiTon** [comment]
@nobeeakon could you try merging master?

**Comment by sumana2001** [comment]
@nobeeakon Yes, I am sorry that was my mistake. I had merged a wrong commit by mistake so Alex had to revert it. It will be merged with the welcome tour PR

> mmmm, well, some PRs are missing in the `master` of the repo. Those other PRs are not mine (2 from @alexfauquette , 2 CI changes from @teolemon ), but existed in the `master` (and at some point were reverted?). @teolemon do you know why those are missing?

**Review by sumana2001 — APPROVED** [review]
LGTM

**Comment by alexfauquette** [comment]
Sorry for the commits issues, I resolved the conflicts

**Pull request merged**
