### PR TITLE
feat: Color palette

### PR DESCRIPTION
**Pull request by alexfauquette**
image

image

image

image

### CODE REVIEW

**Comment by VaiTon** [comment]
@alexfauquette the help tour is displayed two times, one in dark mode and the other, when closing the first one, in light mode

**Comment by alexfauquette** [comment]
@VaiTon I do not manage to reproduce the bug. Could you do a recording?

I did:
- go to settings: https://deploy-preview-403--warm-cannoli-79bbb2.netlify.app/settings
- Switch to the dark mode
- open the help tour
- go to next step and close the tour

**Comment by VaiTon** [comment]
Hey @alexfauquette, sure! You have to clean the localStorage and then refresh the page!


https://user-images.githubusercontent.com/12072630/208312593-7d9751f2-f3b6-419c-9b46-5289e3be3f0e.mp4

**Comment by alexfauquette** [comment]
@VaiTon Thanks for the demo, we had 2 welcome tours, one for desktop and one for mobile. I refactored it to keep only one source of truth

**Review by teolemon — APPROVED** [review]

**Comment by teolemon** [comment]
@alexfauquette ok to merge ? I had one report of the duplicated onboarding, so keen to merge that one

**Pull request merged**
